26/02/21 (13:07:52) | ERROR: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/bpytop.py", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
04/03/21 (18:25:32) | ERROR: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/bpytop.py", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
08/03/21 (20:44:16) | ERROR: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/bpytop.py", line 1327, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/digit/.config/bpytop/themes'
